Rewrote init scripts to base them off of /etc/init.d/skeleton

diff --git a/debian/debpool.init b/debian/debpool.init
--- a/debian/debpool.init
+++ b/debian/debpool.init
@@ -6,84 +6,181 @@
 # Required-Stop:   $local_fs $remote_fs
 # Default-Start:   2 3 4 5
 # Default-Stop:    0 1 6
-# Short-Description: Start Debian package archiver
+# Short-Description: Debian package archiver
 ### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+# Basing script off of /etc/init.d/skeleton
+
+PATH=/usr/sbin:/usr/bin:/sbin:/bin
+DESC="Debian package archiver"
 NAME=debpool
 DAEMON=/usr/bin/$NAME
+SCRIPTNAME=/etc/init.d/$NAME
 DEFAULT=/etc/default/$NAME
-DESC="Debian package archiver"
-test -x $DAEMON || exit 0
 
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r $DEFAULT ] && . $DEFAULT
+
+# Define LSB log_* functions.
 . /lib/lsb/init-functions
 
-# Include debpool defaults if available
-if [ -f $DEFAULT ]; then
-	. $DEFAULT
-fi
-
+# Check if daemon is enabled in default configuration
 if [ "$ENABLED" = "0" ]; then
-	test "$1" = "start" && echo "Not starting $DESC; disabled in $DEFAULT."
+	test "$1" = "start" && \
+	{
+		log_warning_msg "$NAME: Not starting $DESC."
+		log_warning_msg "$NAME: Disabled in $DEFAULT."
+	}
 	exit 0
 fi
 
-# Run as root if USER not specified
-if [ ! $USER ]; then
-	USER=root
+# Run as root if DEBPOOL_USER not specified
+if [ ! $DEBPOOL_USER ]; then
+	DEBPOOL_USER=root
 fi
 
-eval USERHOME=~$USER
+# Check for an invalid user or one without a home directory
+eval USERHOME=~$DEBPOOL_USER
 if [ "${USERHOME#/}" = "${USERHOME}" ]; then
-	echo "$NAME: The user '$USER' specified in $DEFAULT is invalid."
-	log_failure_msg "$NAME: The user '$USER' specified in $DEFAULT is invalid."
+	log_failure_msg "$NAME: The user '$DEBPOOL_USER' specified in $DEFAULT is invalid."
 	exit 1
 fi
 
-PIDFILE=$(HOME=$USERHOME debpool --get_lock_path $LOCKPATH) || {
-	log_failure_msg "$NAME: could not determine lockfile path."
-	exit 1
+# Run as $DEBPOOL_USER if not running as root
+if [ "$DEBPOOL_USER" != "root" ]; then
+	CHUID="--chuid $DEBPOOL_USER"
+fi
+
+# If lock file specified, pass it to debpool with --lock_file
+# else try to determine lock file using Debpool::Config
+if [ "$LOCKFILE" ]; then
+	PIDFILE=$LOCKFILE
+	LOCKFILE="--lock_file $LOCKFILE"
+else
+	LOCKFILE=$(HOME=$USERHOME debpool --get_lock_path) || \
+		{
+			log_failure_msg "$NAME: could not determine lock file path."
+			exit 1
+		}
+	PIDFILE=$LOCKFILE
+	LOCKFILE="--lock_file $LOCKFILE"
+fi
+
+# If log file specified, pass it to debpool with --log_file option
+if [ "$LOGFILE" ]; then
+	LOGFILE="--log_file $LOGFILE"
+fi
+
+# Specify all options to use for debpool
+DAEMON_ARGS="--daemon $LOGFILE $LOCKFILE $OPTIONS"
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE \
+		--startas $DAEMON $CHUID --test > /dev/null || \
+		return 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE \
+		--startas $DAEMON $CHUID -- $DAEMON_ARGS || \
+		return 2
 }
 
-if [ -n "$USER" ]; then
-	CHUID="--chuid $USER"
-fi
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+# TODO: Handling a proper reload of debpool will be supported someday.
+# Until then, debpool will just be stopped and restarted.
+#
+# do_reload() {
+# 	#
+# 	# If the daemon can reload its configuration without
+# 	# restarting (for example, when it is sent a SIGHUP),
+# 	# then implement that here.
+# 	#
+# 	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+# 	return 0
+# }
 
 case "$1" in
-	start)
-		log_daemon_msg "Starting $DESC" "$NAME"
-		start-stop-daemon --start --quiet --pidfile $PIDFILE \
-			--exec $DAEMON $CHUID -- --daemon $LOGFILE $LOCKPATH $OPTIONS
-		log_end_msg $?
+  start)
+	log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0) log_end_msg 0 ;;
+		1) log_warning_msg "$DESC" "'$NAME'" "was already started" ;;
+		2) log_end_msg 1 ;;
+	esac
+	;;
+  stop)
+	log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0) log_end_msg 0 ;;
+		1) log_warning_msg "$DESC" "'$NAME'" "was already stopped" ;;
+		2) log_end_msg 1 ;;
+	esac
+	;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
 		;;
-	stop)
-		log_daemon_msg "Stopping $DESC" "$NAME"
-		start-stop-daemon --stop --quiet --pidfile $PIDFILE \
-			--oknodo --name $NAME
-		log_end_msg $?
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
 		;;
-	force-reload)
-		# check wether $DAEMON is running. If so, restart
-		start-stop-daemon --stop --test --quiet --pidfile \
-			$PIDFILE --name $NAME \
-			&& exec $0 restart \
-			exit 0
-		;;
-	restart)
-		log_daemon_msg "Restarting $DESC" "$NAME"
-		start-stop-daemon --stop --quiet --pidfile $PIDFILE \
-			--oknodo --name $NAME
-		sleep 1
-		start-stop-daemon --start --quiet --pidfile $PIDFILE \
-			--exec $DAEMON $CHUID -- --daemon $LOGFILE $LOCKPATH $OPTIONS
-		log_end_msg $?
-		;;
-	*)
-		N=/etc/init.d/$NAME
-		# echo usage information
-		echo "Usage: $N {start|stop|restart|force-reload}" >&2
-		exit 2
-		;;
+	esac
+	;;
+  *)
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit 0
+:
